E-Learning/Models/Cart/Cart.cs
using System.ComponentModel.DataAnnotations;

namespace E_Learning.Models.Cart
{
    public class Cart
    {

        [Key]
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string InstructorName { get; set; }
        public string Email { get; set; }
        public double Price { get; set; }
        public int Duration { get; set; }
    }
}

E-Learning/Models/Cart/PurchaseOrder.cs
using System.ComponentModel.DataAnnotations;

namespace E_Learning.Models.Cart
{
    public class PurchaseOrder
    {
        [Key]
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string InstructorName { get; set; }
        public string Email { get; set; }
        public double Price { get; set; }
   
        public int Duration { get; set; }

        // Add properties for PurchasedDate and EndDate
        public string PurchasedDate { get; set; }
        public string EndDate { get; set; }
    }   
}

E-Learning/Models/Course/AddCourseCategory.cs
using System.ComponentModel.DataAnnotations;

namespace E_Learning.Models.Course
{
    public class AddCourseCategory
    {
        [Key]
        public int Id { get; set; }
        public string CourseName { get; set; }

        public string CourseDescription { get; set; }

        public string Level { get; set; }

        public string InstructorName { get; set; }

        public string Thumbnail { get; set; }

        public double Price { get; set; }

        public string CreatedAt { get; set; } = DateTime.Now.ToString("dd-MM-yyyy");

        public string? Tag { get; set; }


        public int Duration { get; set; }
    }

    public class EmailRequest
    {
        [Key]
        public int id { get; set; }

        public List<string> ToEmails { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }

    }
}

E-Learning/Models/Course/AddCourseContent.cs
using System.ComponentModel.DataAnnotations;

namespace E_Learning.Models.Course
{
    public class AddCourseContent
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string MetaUrl { get; set; }
        public string SubCourse { get; set; }
        public string CourseName { get; set; } // Drop Down from Admin Course Table 
        public string Question { get; set; }

    }
}

E-Learning/Models/Course/CertificateViewModel.cs
namespace E_Learning.Models.Course
{
    public class CertificateViewModel
    {
        public string UserName { get; set; }
        public string CourseName { get; set; }

        public string Date { get; set; }
    }
}

E-Learning/Models/Course/CourseContentQuizViewModel.cs
namespace E_Learning.Models.Course
{
    public class CourseContentQuizViewModel
    {
        public List<AddCourseContent> CourseContent { get; set; }
        public List<Quiz> Quizzes { get; set; }
    }
}

E-Learning/Models/Course/CourseNameClass.cs
namespace E_Learning.Models.Course
{
	public class CourseNameClass
	{
		string CourseName { get; set; }
	}
}

E-Learning/Models/Course/Quiz.cs
using System.ComponentModel.DataAnnotations;

namespace E_Learning.Models.Course
{
    public class Quiz
    {
        [Key]
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string Subcourse { get; set; }
        public string title { get; set; }
        public string question { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string answer { get; set; }
    }
}

E-Learning/Models/Dashboard/CombinedViewModel.cs
namespace E_Learning.Models.Dashboard
{
    public class CombinedViewModel
    {
        public List<RegistrationData> RegistrationData { get; set; }
        public List<MonthlyAmountViewModel> MonthlyAmountData { get; set; }

        public int TotalRegisteredStudents { get; set; }
        public decimal TotalRevenue { get; set; }
    }
}

E-Learning/Models/Dashboard/MonthlyAmountViewModel.cs
namespace E_Learning.Models.Dashboard
{
    public class MonthlyAmountViewModel
    {
        public string Month { get; set; }
        public string MonthName { get; set; }
        public double TotalAmount { get; set; }
    }
}

E-Learning/Models/Dashboard/RegistrationData.cs
namespace E_Learning.Models.Dashboard
{
    public class RegistrationData
    {
        public int Year { get; set; }
        public int Month { get; set; }
        public string MonthName { get; set; }
        public int Count { get; set; }
    }
}

E-Learning/Controllers/HomePageController.cs
using E_Learning.Models.Cart;
using E_Learning.Models.Comments;
using E_Learning.Models.Course;
using E_Learning.Models.Promotion;
using E_Learning.Models.Review;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace E_Learning.Controllers
{
    [Authorize]
    public class HomePageController : Controller
    {
        private readonly HttpClient client;

        public HomePageController()
        {

            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            client = new HttpClient(clientHandler);
        }
        
        public IActionResult Index()
        {

            // promotion url ->https://localhost:44342/api/Promotion/GetPromotion
            string url = "https://localhost:44342/api/Promotion/GetPromotion";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                string jsondata = response.Content.ReadAsStringAsync().Result;
                var courses = JsonConvert.DeserializeObject<List<Promotion>>(jsondata);
                return View(courses);
            }

            return View();
           
        }
        // ------------------------------------------------ Course Manangement 
        public IActionResult Courses()    // Call API 
        {
            string url = "https://localhost:44342/api/Course/GetAllCourse";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                string jsondata = response.Content.ReadAsStringAsync().Result;
                var courses = JsonConvert.DeserializeObject<List<AddCourseCategory>>(jsondata);
                return View(courses);
            }

            return View();
        }

        public IActionResult AboutUs()
        {
            return View();
        }

        // ------------------------------------------------ Quiz Manangement 

        [HttpPost]
        public IActionResult ONE()
        {
            var id = Request.Form["Id"];  // here is posting data fron view to action 
            HttpContext.Session.SetString("id", id);
            return RedirectToAction("CourseMainDetails");
        }

        /*    public IActionResult CourseMainDetails()

			{
				 int obj = int.Parse(HttpContext.Session.GetString("id"));

				string url = $"https://localhost:44342/api/Course/GetCourseById/{obj}";
				HttpResponseMessage response = client.GetAsync(url).Result;

				if (response.IsSuccessStatusCode)
				{
					string jsondata = response.Content.ReadAsStringAsync().Result;
					var course = JsonConvert.DeserializeObject<AddCourseCategory>(jsondata);
					return View(course);
				}
				return View();
			}*/
        /*public IActionResult CourseMainDetails()
		{
			int obj = int.Parse(HttpContext.Session.GetString("id"));

			string url = $"https://localhost:44342/api/Course/GetCourseById/{obj}";
			HttpResponseMessage response = client.GetAsync(url).Result;

			if (response.IsSuccessStatusCode)
			{
				string jsondata = response.Content.ReadAsStringAsync().Result;
				var course = JsonConvert.DeserializeObject<AddCourseCategory>(jsondata);

				// Fetch comments for the course
				string commentsUrl = $"https://localhost:44342/api/Comments/GetCommentsByCourseName?courseName={course.CourseName}";
				HttpResponseMessage commentsResponse = client.GetAsync(commentsUrl).Result;

                // Fetch reviews for the course
                string reviewsUrl = $"https://localhost:44342/api/Review/GetReviewsByCourseName?courseName={course.CourseName}";
                HttpResponseMessage reviewsResponse = client.GetAsync(reviewsUrl).Result;
                  
				List<Comments> comments = new List<Comments>();
				if (commentsResponse.IsSuccessStatusCode)
				{
					string commentsJsonData = commentsResponse.Content.ReadAsStringAsync().Result;
					comments = JsonConvert.DeserializeObject<List<Comments>>(commentsJsonData);
				}

				// Create the view model
				var viewModel = new CourseDetailsViewModel
				{
					Course = course,
					Comments = comments,
                    Rating = // here store the average rating of the course
				};

				return View(viewModel);
			}
			return View();
		}*/


        public IActionResult CourseMainDetails()
        {
            int obj = int.Parse(HttpContext.Session.GetString("id"));

            string url = $"https://localhost:44342/api/Course/GetCourseById/{obj}";
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                string jsonData = response.Content.ReadAsStringAsync().Result;
                var course = JsonConvert.DeserializeObject<AddCourseCategory>(jsonData);

                // Fetch comments for the course
                string commentsUrl = $"https://localhost:44342/api/Comments/GetCommentsByCourseName?courseName={course.CourseName}";
                HttpResponseMessage commentsResponse = client.GetAsync(commentsUrl).Result;

                List<Comments> comments = new List<Comments>();
                if (commentsResponse.IsSuccessStatusCode)
                {
                    string commentsJsonData = commentsResponse.Content.ReadAsStringAsync().Result;
                    comments = JsonConvert.DeserializeObject<List<Comments>>(commentsJsonData);
                }

                // Fetch average rating for the course
                string reviewsUrl = $"https://localhost:44342/api/Review/GetReviewAvg?courseName={course.CourseName}";
                HttpResponseMessage reviewsResponse = client.GetAsync(reviewsUrl).Result;

                int averageRating = 0;
                if (reviewsResponse.IsSuccessStatusCode)
                {
                    string reviewsJsonData = reviewsResponse.Content.ReadAsStringAsync().Result;
                    double averageRatingDouble = JsonConvert.DeserializeObject<double>(reviewsJsonData);
                    averageRating = (int)Math.Round(averageRatingDouble);
                }

                // Create the view model
                var viewModel = new CourseDetailsViewModel
                {
                    Course = course,
                    Comments = comments,
                    Rating = averageRating
                };

                return View(viewModel);
            }
            return View();
        }


        public IActionResult ContactUs()
        {
            return View();
        }
       
        // ------------------------------------------------  Cart Managment 

        public IActionResult Cart()
        {
            // Get Api
            // url -> https://localhost:44342/api/Cart/FetchCart?Email=khrish%40gmail
            var userEmail = HttpContext.Session.GetString("UserEmail");
            var url = $"https://localhost:44342/api/Cart/FetchCart?Email={userEmail}";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                string jsondata = response.Content.ReadAsStringAsync().Result;
                var course = JsonConvert.DeserializeObject<List<Cart>>(jsondata);
                return View(course);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cart(string CourseName, string InstructorName, double Price ,int Duration)
        {
            // Get User Email from Session
            var userEmail = HttpContext.Session.GetString("UserEmail");
            var data = new Cart
            {
                Email = userEmail,
                InstructorName = InstructorName,
                CourseName = CourseName,
                Price = Price,
                Duration = Duration
            };
            // api cart 
            string url = "https://localhost:44342/api/Cart/AddToCart";
            var jsondata = JsonConvert.SerializeObject(data);
            StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                // Toster For notification (Optional)
                TempData["SuccessMessage"] = "Your course has been added to the cart successfully!";
                return RedirectToAction("CourseMainDetails");
            }


            return View();
        }

        public IActionResult RemoveCartItem(int id)
        {
            // Your logic to remove the item from the cart using the id
            // url -> https://localhost:44342/api/Cart/DeleteItem/15

            string url = $" https://localhost:44342/api/Cart/DeleteItem/{id}";
            HttpResponseMessage response = client.DeleteAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Cart");
            }
            return RedirectToAction("Cart");
        }
    
    
      // ---------------------------------------------- PDF View
      public IActionResult Invoice() {
            return View();
        }


        // ------------------------- PlaceOrder function
        [HttpPost]
        public async Task<IActionResult> PlaceOrderFun()
        {
            var userEmail = HttpContext.Session.GetString("UserEmail");
            var url = $"https://localhost:44342/api/Cart/ProceedToOrder?Email={userEmail}";
            HttpResponseMessage response = await client.PostAsync(url, null);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    
    
        // --------------------------------  USER DASHBOARD

E-Learning/Views/HomePage/AboutUs.cshtml
@{
    ViewData["Title"] = "AboutUs";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h1>AboutUs</h1>

E-Learning/Views/HomePage/Cart.cshtml
@model List<E_Learning.Models.Cart.Cart>
@{
    ViewData["Title"] = "Cart";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
    double totalPrice = Model != null && Model.Any() ? Model.Sum(item => item.Price) : 0;
}

<!-- bread crumb area -->
<div class="rts-bread-crumbarea-1 rts-section-gap bg_image">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-main-wrapper">
                    <h1 class="title">Cart</h1>
                    <!-- breadcrumb pagination area -->
                    <div class="pagination-wrapper">
                        <a asp-action="Index" asp-controller="HomePage">Home</a>
                        <i class="fa-regular fa-chevron-right"></i>
                        <a class="active" href="#">Cart</a>
                    </div>
                    <!-- breadcrumb pagination area end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- bread crumb area end -->
<!-- Shop area start -->
<main class="ms-main container">
    <div class="ms-page-content">
        <!--================= Cart Area Start =================-->
        <article id="post-283" class="post-283 page type-page status-publish hentry">
            <div class="ms-default-page container">
                <div class="woocommerce">
                    <div class="woocommerce-notices-wrapper"></div>
                    <div class="ms-woocommerce-cart-form-wrapper row">
                        <table class="shop_table shop_table_responsive cart woocommerce-cart-form__contents col-6 me-5 mt-5">
                            <thead>
                                <tr>
                                    <th class="product-remove">Img</th>
                                    <th class="product-thumbnail">Course Name</th>
                                    <th class="product-name">Instructor Name</th>
                                    <th class="product-name">Price</th>
                                    <th class="product-price"></th>
                                </tr>
                            </thead>
                            <tbody>

                                @if (Model != null && Model.Any())
                                {

                                    @foreach (var d in Model)
                                    {
                                        <tr class="woocommerce-cart-form__cart-item cart_item">
                                            <td class="product-thumbnail">
                                                <i class="fa fa-book" style="font-size:30px"></i>
                                            </td>
                                            <td class="product-name">
                                                @d.CourseName
                                            </td>
                                            <td class="product-name" data-title="Product">
                                                @d.InstructorName
                                            </td>
                                            <td class="product-price" data-title="Price">
                                                <span class="woocommerce-Price-amount amount">
                                                    @d.Price
                                                </span>
                                            </td>
                                            <td class="product-remove">
                                                <a asp-action="RemoveCartItem" asp-route-id="@d.Id" class="remove" aria-label="Remove this item">
                                                    <svg viewBox="0 0 200 200" width="18" xmlns="http://www.w3.org/2000/svg">
                                                        <path d="M114,100l49-49a9.9,9.9,0,0,0-14-14L100,86,51,37A9.9,9.9,0,0,0,37,51l49,49L37,149a9.9,9.9,0,0,0,14,14l49-49,49,49a9.9,9.9,0,0,0,14-14Z">
                                                        </path>
                                                    </svg>
                                                </a>
                                            </td>
                                        </tr>
                                    }

                                }

                            </tbody>
                        </table>
                        <div class="col-1">
                        </div>
                        <div class="col-4">
                            <div class="ms-cart-collaterals cart-collaterals">
                                <div class="ms-cart-totals cart_totals">
                                    <h3 class="animated fadeIn">Cart totals</h3>
                                    <table class="shop_table shop_table_responsive">
                                        <tbody>
                                            <tr class="cart-subtotal">
                                                <th>Subtotal</th>
                                                <td data-title="Subtotal">
                                                    <span class="woocommerce-Price-amount amount">
                                                        <bdi><span class="woocommerce-Price-currencySymbol">₹</span>@totalPrice</bdi>
                                                    </span>
                                                </td>
                                            </tr>
                                            <tr class="order-total">
                                                <th>Total</th>
                                                <td data-title="Total">
                                                    <strong>
                                                        <span class="woocommerce-Price-amount amount">
                                                            <bdi><span class="woocommerce-Price-currencySymbol">₹</span>@totalPrice</bdi>
                                                        </span>
                                                    </strong>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="ms-proceed-to-checkout wc-proceed-to-checkout">
                                        <a href="javascript:void(0);" class="rts-btn btn-primary" onclick="openRazorpay(@totalPrice * 100)">Proceed to checkout</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="">
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </article>
        <!--================= Cart Area End =================-->
        <!--================= Services Area Start =================-->
        <!--================= Services Area End =================-->
    </div>
</main>

<!-- Hidden form to submit payment details -->
<form id="razorpayForm" action="@Url.Action("PlaceOrderFun", "HomePage")" method="post">
    <input type="hidden" id="payment_id" name="payment_id" />
    <input type="hidden" id="payment_status" name="payment_status" />
</form>

 
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
        function openRazorpay(amountInPaise) {
            var options = {
                "key": "rzp_test_UMVGiuA5sKQxEW", // Replace with your actual Razorpay key
                "amount": amountInPaise, // Amount is in paise (100 paise = ₹1)
                "currency": "INR", // Use INR for Indian Rupees
                "name": "Your Company",
                "description": "Purchase Description",
                "image": "https://your_logo_url", // Optional: Your company logo URL
                "handler": function (response) {
                    document.getElementById('payment_id').value = response.razorpay_payment_id;
                    document.getElementById('payment_status').value = 'Success'; // Or use the actual status if available
                    document.getElementById('razorpayForm').submit();
                },
                "prefill": {
                    "name": "Customer Name",
                    "email": "customer.email@example.com",
                    "contact": "9876543210"
                },
                "theme": {
                    "color": "#3399cc"
                }
            };

            var rzp1 = new Razorpay(options);
            rzp1.open();
        }
    </script>
 

E-Learning/Views/HomePage/Certificate.cshtml
@model E_Learning.Models.Course.CertificateViewModel
@{
    ViewData["Title"] = "Certificate";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<style>
    .certificate-container {
        border: 5px solid #ddd;
        padding: 20px;
        margin: 50px auto;
        max-width: 800px;
        text-align: center;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }

    .certificate-header {
        font-size: 2.5em;
        font-weight: bold;
        color: #4CAF50;
        margin-bottom: 20px;
    }

    .certificate-body {
        font-size: 1.2em;
        margin-bottom: 30px;
    }

        .certificate-body span {
            font-weight: bold;
        }

    .certificate-footer {
        font-size: 1em;
        color: #555;
    }
</style>

<div class="container" id="certificate">
    <div class="certificate-container">
        <div class="certificate-background mb-5">
            <img src="../adminassets/img/masstech-logo.png" width="300px" alt="Company Logo" class="background-logo" />
        </div>
        <div class="certificate-header">
            Certificate of Completion
        </div>
        <div class="certificate-body">
            <p class="mb-2">This is to certify that</p>
            <h2>@Model.UserName</h2>
            <p class="mb-2">has successfully completed the course</p>
            <h2>@Model.CourseName</h2>
            <p class="mb-2">on</p>
            <h4>@Model.Date</h4>
        </div>
        <div class="certificate-footer">
            <p>Masstech Edu Platform</p>
        </div>
    </div>
</div>
<p class="text-center"><button class="btn btn-success" onclick="downloadPDF()" style="width:150px">Download Certificate</button></p>

<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.min.js"></script>

@{
    <script>
        function downloadPDF() {
            const element = document.getElementById('certificate');
            const opt = {
                margin: 0.5,
                filename: 'Certificate.pdf',
                image: { type: 'jpeg', quality: 1 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
            };

            html2pdf().set(opt).from(element).save().then(() => {
                // You can add any logic to execute after PDF download here
            });
        }

    </script>
}

E-Learning/Views/HomePage/ContactUs.cshtml
@{
    ViewData["Title"] = "ContactUs";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!-- bread crumb area -->
<div class="rts-bread-crumbarea-1 rts-section-gap bg_image">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-main-wrapper">
                    <h1 class="title">Contact Us</h1>
                    <!-- breadcrumb pagination area -->
                    <div class="pagination-wrapper">
                        <a asp-action="Index" asp-controller="HomePage">Home</a>
                        <i class="fa-regular fa-chevron-right"></i>
                        <a class="active" href="#">Contact us</a>
                    </div>
                    <!-- breadcrumb pagination area end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- bread crumb area end -->
<!-- rts contact area start -->
<div class="rts-contact-area rts-section-gapTop">
    <div class="container">
        <div class="row g-5">
            <div class="col-xl-5">
                <!-- contact left area start -->
                <div class="contact-left-area-start">
                    <div class="title-area-left-style">
                        <div class="pre-title">
                            <img src="../assets/images/banner/bulb.png" alt="icon">
                            <span>Courses</span>
                        </div>
                        <h2 class="title">
                            Love to hear from you <br>
                            <span>Get in touch!</span>
                        </h2>
                    </div>
                    <form action="https://html.themewant.com/studyhub/mailer.php" method="post" class="contact-page-form" id="contact-form">
                        <div class="single-input">
                            <label for="name">Your Name*</label>
                            <input id="name" name="name" type="text" placeholder="Andrew Davis ...." required>
                        </div>
                        <div class="single-input">
                            <label for="email">Your Email*</label>
                            <input id="email" name="email" type="email" placeholder="info@studyhub.net">
                        </div>
                        <div class="single-input">
                            <label for="message">Message*</label>
                            <textarea id="message" name="message" placeholder="Let tell us about your projects"></textarea>
                        </div>
                        <button class="rts-btn btn-primary mt--30">Send Message</button>
                    </form>
                    <div id="form-messages" class="mt--20"></div>
                </div>
                <!-- contact left area end -->
            </div>
            <div class="col-xl-7 pl--50 pl_lg--15 pl_md--15 pl_sm--15 pb_md--100 pb_sm--100">
                <div class="contact-map-area-start">
                    <div class="single-maptop-info">
                        <div class="icon">
                            <img src="../assets/images/contact/02.png" alt="contact">
                        </div>
                        <p class="disc">
                            708 Fenkin 9,
                            Mulund Thane CheckNaka, Thane 400604
                        </p>
                    </div>
                    <div class="single-maptop-info">
                        <div class="icon">
                            <img src="../assets/images/contact/03.png" alt="contact">
                        </div>
                        <a href="tel:+918108296510">(+91) 81082 96510</a> <br>
                        <a href="tel:+918108296510">(+91) 81082 96510</a>
                    </div>
                    <div class="single-maptop-info">
                        <div class="icon">
                            <img src="../assets/images/contact/04.png" alt="contact">
                        </div>
                        <p class="disc">
                            Mon-Fri: 9 AM – 6 PM <br>
                            Saturday: 9 AM – 4 PM
                        </p>
                    </div>
                </div>
                <div class="map-bottom-area mt--30">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d60305.60734072531!2d72.87997215775525!3d19.14707941025751!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b9048b5a1eb1%3A0xf4a266dc22737c5!2sMasstech%20Business%20Solutions%20Pvt%20Ltd!5e0!3m2!1sen!2sin!4v1720632085791!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- rts contact area end -->

<div class="rts-section-gap">

</div>

E-Learning/Views/HomePage/Invoice.cshtml
@{
    ViewData["Title"] = "Invoice";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h1>Invoice</h1>