E-Learning/Controllers/AdminController.cs
using E_Learning.Models.Cart;
using E_Learning.Models.Course;
using E_Learning.Models.Dashboard;
using E_Learning.Models.Comments;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using System.Text.Json;

using E_Learning.Models.Auth;

namespace E_Learning.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly HttpClient client;
        public AdminController()
        {
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            client = new HttpClient(clientHandler);
            client = new HttpClient(clientHandler)
            {
                BaseAddress = new System.Uri("https://localhost:44342/api/Course/") // Base URL of the external API 
            };
        }


        public async Task<IActionResult> Index()
        {

            // Consume first API
            var registrationResponse = await client.GetAsync("https://localhost:44342/api/Chart/registrations-per-month");
            if (!registrationResponse.IsSuccessStatusCode)
            {
                // Handle error
                return View("Error");
            }
            var registrationJsonString = await registrationResponse.Content.ReadAsStringAsync();
            var registrationData = System.Text.Json.JsonSerializer.Deserialize<List<RegistrationData>>(registrationJsonString, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

            // Consume second API
            var monthlyAmountResponse = await client.GetAsync("https://localhost:44342/api/Chart/MonthlyTotals");
            if (!monthlyAmountResponse.IsSuccessStatusCode)
            {
                // Handle error
                return View("Error");
            }
            var monthlyAmountJsonString = await monthlyAmountResponse.Content.ReadAsStringAsync();
            var monthlyAmountData = System.Text.Json.JsonSerializer.Deserialize<List<MonthlyAmountViewModel>>(monthlyAmountJsonString, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

            var viewModel = new CombinedViewModel
            {
                RegistrationData = registrationData,
                MonthlyAmountData = monthlyAmountData,
                TotalRegisteredStudents = registrationData.Sum(r => r.Count), // Calculate total registered
                TotalRevenue = monthlyAmountData.Sum(m => (decimal)m.TotalAmount)
            };

            return View(viewModel);
        }

        public IActionResult AddMaterial()
        {
            return View();
        }

        // ------------------------------------------------- Course Manuplation
        public IActionResult AddCourse()
        {
            return View();
        }

        /*[HttpPost]
		public IActionResult AddCourse(AddCourseCategory addcate)
		{
			string url = "https://localhost:44342/api/Course/AddCategory";
			var jsondata = JsonConvert.SerializeObject(addcate);
			StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
			HttpResponseMessage response = client.PostAsync(url, content).Result;
			if (response.IsSuccessStatusCode)
			{
				TempData["SuccessMessage"] = "Course added successfully!";
				return RedirectToAction("AddCourse"); // Redirect to avoid form resubmission

			}
			else
			{
				TempData["ErrorMessage"] = "Failed to add course.";
				return RedirectToAction("AddCourse");
			}
		}*/


        public IActionResult AddCourseCont()
        {
            // here calling api 
            string url = "https://localhost:44342/api/Course/GetCourseName";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                string jsondata = response.Content.ReadAsStringAsync().Result;
                var courseNames = JsonConvert.DeserializeObject<List<string>>(jsondata);
                if (courseNames != null)
                {
                    ViewBag.CourseNames = courseNames;
                    return View();
                }
            }
            return View();
        }


        [HttpPost]

        public async Task<IActionResult> AddCourseAsync(AddCourseCategory addcate)
        {
            string url = "https://localhost:44342/api/Course/AddCategory";
            var jsondata = JsonConvert.SerializeObject(addcate);
            StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");

            HttpResponseMessage response = await client.PostAsync(url, content);

            if (response.IsSuccessStatusCode)
            {
                var users = await client.GetFromJsonAsync<IEnumerable<Users>>("https://localhost:44342/api/Auth/GetAllUsers");

                if (users != null)
                {
                    var emailRequest = new EmailRequest
                    {
                        ToEmails = users.Select(u => u.Email).ToList(),
                        Subject = "Exciting New Course Available at an Unbeatable Price!",
                        Body = $@"
                    <p>Dear User,</p>
                    <p>We are thrilled to announce the launch of our brand new course: <strong>{addcate.CourseName}</strong>!</p>
                    <h3>Why You Should Enroll:</h3>
                    <ul>
                        <li><strong>Engaging Content:</strong> Our course is packed with practical insights and engaging content designed to help you master {addcate.CourseName}.</li>
                        <li><strong>Expert Instructor:</strong> Learn from the best in the field, with guiding you through every step of the way.</li>
                        <li><strong>Affordable Pricing:</strong> At just {addcate.Price}, you get access to top-quality education without breaking the bank. We believe in providing value, and our pricing reflects that commitment.</li>
                        <li><strong>Flexible Learning:</strong> Learn at your own pace with our flexible online platform. Whether you prefer to study in the mornings, evenings, or weekends, this course is designed to fit into your schedule.</li>
                    </ul>
                    <h3>Course Highlights:</h3>
                    <ul>
                        <li><strong>Comprehensive Curriculum:</strong> Covering all the essential topics you need to succeed.</li>
                        <li><strong>Interactive Sessions:</strong> Engage with the instructor and fellow students through live Q&A sessions.</li>
                        <li><strong>Hands-on Projects:</strong> Apply what you've learned in real-world scenarios.</li>
                    </ul>
                    <h3>Special Launch Offer:</h3>
                    <p>To celebrate the launch of <strong>{addcate.CourseName}</strong>, we are offering an exclusive discount for the first 30 enrollees. Don't miss out on this opportunity to enhance your skills at an unbeatable price!</p>
                    <h3>How to Enroll:</h3>
                    <ol>
                        <li><strong>Visit our website:</strong> [Insert Website Link]</li>
                        <li><strong>Register:</strong> Create an account or log in if you already have one.</li>
                        <li><strong>Enroll in the Course:</strong> Find <strong>{addcate.InstructorName}</strong> and click 'Enroll Now'.</li>
                        <li><strong>Start Learning:</strong> Begin your journey to mastering {addcate.CourseDescription}.</li>
                    </ol>
                    <p>We can't wait to see you in the course!</p>
                    <p>Best regards,<br>The Masstech Team</p>
                    <p><strong>P.S.</strong> Have questions? Feel free to reply to this email or visit our FAQ page/Contact Us page for more information.</p>"
                    };

                    var emailResponse = await client.PostAsJsonAsync("https://localhost:44342/api/Email/send", emailRequest);

                    if (!emailResponse.IsSuccessStatusCode)
                    {
                        TempData["ErrorMessage"] = "Failed to send email notification.";
                    }
                }
                else
                {
                    TempData["ErrorMessage"] = "Failed to fetch users.";
                }

                TempData["SuccessMessage"] = "Course added successfully!";
            }
            else
            {
                TempData["ErrorMessage"] = "Failed to add course.";
            }

            return RedirectToAction("AddCourse"); // Redirect to avoid form resubmission
        }

        [HttpPost]
        public IActionResult AddCourseCont(AddCourseContent addcont)
        {
            string url = "https://localhost:44342/api/Course/AddContent";
            var jsondata = JsonConvert.SerializeObject(addcont);
            StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessMessage"] = "Sub Category added successfully";
                return RedirectToAction("AddCourseCont");
            }
            else
            {
                TempData["ErrorMessage"] = "Failed to add sub category.";
                return RedirectToAction("AddCourseCont");
            }
        }



        //--------------------------------------------------------------------Abhang
        public async Task<IActionResult> AddQuizes()
        {
            var courseNames = await client.GetFromJsonAsync<List<string>>("GetCourseNameABH");
            ViewBag.CourseNames = courseNames;

E-Learning/Controllers/NotifyController.cs
using E_Learning.Models.Auth;
using E_Learning.Models.Course;
using E_Learning.Models.Notification;
using E_Learning.Models.Promotion;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace E_Learning.Controllers
{
    [Authorize]
    public class NotifyController : Controller
    {

        HttpClient client;
        public NotifyController()
        {
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };

            client = new HttpClient(clientHandler);
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddNotification(Notification notification)
        {
            string url = "https://localhost:44342/api/Notification/PostNotification";
            var jsondata = JsonConvert.SerializeObject(notification);
            StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
            HttpResponseMessage response = await client.PostAsync(url, content);

            if (response.IsSuccessStatusCode)
            {
                // Fetch users
                var users = await client.GetFromJsonAsync<IEnumerable<Users>>("https://localhost:44342/api/Auth/GetAllUsers");

                if (users != null)
                {
                    var emailRequest = new EmailRequest
                    {
                        ToEmails = users.Select(u => u.Email).ToList(),
                        Subject = "New Notification: " + notification.Title,
                        Body = $@"
                    <p>Dear User,</p>
                    <p>We are excited to bring to your attention a new notification: <strong>{notification.Title}</strong>.</p>
                    <p><strong>Details:</strong></p>
                    <p>{notification.Content}</p>
                    <p>Best regards,<br>The Masstech Team</p>
                    <p><strong>P.S.</strong> Have questions? Feel free to reply to this email or visit our FAQ page/Contact Us page for more information.</p>
                        "
                    };

                    var emailResponse = await client.PostAsJsonAsync("https://localhost:44342/api/Email/send", emailRequest);

                    if (emailResponse.IsSuccessStatusCode)
                    {
                        TempData["SuccessMessage"] = "Notification created and email sent successfully!";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Notification created but failed to send email.";
                    }
                }
                else
                {
                    TempData["ErrorMessage"] = "Notification created but failed to fetch users.";
                }

                return RedirectToAction("Index");
            }

            TempData["ErrorMessage"] = "Failed to create notification.";
            return View(notification); // Return the model to preserve input
        }

        //[HttpPost]
        //public IActionResult AddNotification(Notification notification)
        //{
        //    string url = "https://localhost:44342/api/Notification/PostNotification";
        //    var jsondata = JsonConvert.SerializeObject(notification);
        //    StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
        //    HttpResponseMessage response = client.PostAsync(url, content).Result;

        //    if (response.IsSuccessStatusCode)
        //    {
        //        TempData["SuccessMessage"] = "Notification created successfully!";
        //        return RedirectToAction("Index");
        //    }

        //    TempData["ErrorMessage"] = "Failed to create notification.";
        //    return View(notification); // Return the model to preserve input
        //}



        public IActionResult AddPromotion()
        {
            return View();
        }


        [HttpPost]
        public IActionResult CreatePromotion(Promotion promotion)
        {
            string url = "https://localhost:44342/api/Promotion/PostPromotion";
            var jsondata = JsonConvert.SerializeObject(promotion);
            StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessMessage"] = "Promotion created successfully!";
                return RedirectToAction("AddPromotion");
            }

            TempData["ErrorMessage"] = "Failed to create promotion.";
            return View(promotion); // Return the model to preserve input
        }



    }
}

E-Learning/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
	<title>Preskool - Dashboard</title>

	<!-- Favicon -->
	<link rel="shortcut icon" href="../AdminAssets/img/Masstech-Logo-Small.png">

	<!-- Fontfamily -->
	<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&amp;display=swap" rel="stylesheet">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="../AdminAssets/css/bootstrap.min.css">

	<!-- Feathericon CSS -->
	<link rel="stylesheet" href="../AdminAssets/plugins/feather/feather.css">

	<!-- Pe7 CSS -->
	<link rel="stylesheet" href="../AdminAssets/plugins/icons/flags/flags.css">

	<!-- Fontawesome CSS -->
	<link rel="stylesheet" href="../AdminAssets/plugins/fontawesome/css/fontawesome.min.css">
	<link rel="stylesheet" href="../AdminAssets/plugins/fontawesome/css/all.min.css">

	<!-- Main CSS -->
	<link rel="stylesheet" href="../AdminAssets/css/style.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<!-- TOSTART -->
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>

	<!-- Main Wrapper -->
	<div class="main-wrapper">

		<!-- Header -->
		<div class="header">

			<!-- Logo -->
			<div class="header-left">
				<a href="index.html" class="logo">
					<img src="../AdminAssets/img/Masstech-Logo.png" alt="Logo">
				</a>
				<a href="index.html" class="logo logo-small">
					<img src="../AdminAssets/img/Masstech-Logo-Small.png" alt="Logo" width="30" height="30">
				</a>
			</div>
			<!-- /Logo -->

			<div class="menu-toggle">
				<a href="javascript:void(0);" id="toggle_btn">
					<i class="fas fa-bars"></i>
				</a>
			</div>

			<!-- Search Bar -->
			@* <div class="top-nav-search">
				<form>
					<input type="text" class="form-control" placeholder="Search here">
					<button class="btn" type="submit"><i class="fas fa-search"></i></button>
				</form>
			</div> *@
			<!-- /Search Bar -->
			<!-- Mobile Menu Toggle -->
			<a class="mobile_btn" id="mobile_btn">
				<i class="fas fa-bars"></i>
			</a>
			<!-- /Mobile Menu Toggle -->
			<!-- Header Right Menu -->
			<ul class="nav user-menu">
				
				
				<li class="nav-item zoom-screen me-2">
					<a href="#" class="nav-link header-nav-list win-maximize">
						<img src="../AdminAssets/img/icons/header-icon-04.svg" alt="">
					</a>
				</li>

				<!-- User Menu -->
				<li class="nav-item dropdown has-arrow new-user-menus">
					<a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
						<div class="user-img">
							<img class="rounded-circle" src="../AdminAssets/img/profiles/avatar-01.jpg" width="31" alt="Ryan Taylor">
							<div class="user-text">
								<h6>Hello Admin</h6>
								<p class="text-muted mb-0">Administrator</p>
							</div>
						</div>
					</a>
					<div class="dropdown-menu">
						<div class="user-header">
							<div class="avatar avatar-sm">
								<img src="../AdminAssets/img/profiles/avatar-01.jpg" alt="User Image" class="avatar-img rounded-circle">
							</div>
							<div class="user-text">
								<h6>Hello Admin</h6>
								<p class="text-muted mb-0">Administrator</p>
							</div>
						</div>
						<a asp-action="Signout" asp-controller="Auth" class="dropdown-item">LogOut</a>
					</div>
				</li>
				<!-- /User Menu -->

			</ul>
			<!-- /Header Right Menu -->

		</div>
		<!-- /Header -->
		<!-- Sidebar -->
		<div class="sidebar" id="sidebar">
			<div class="sidebar-inner slimscroll">
				<div id="sidebar-menu" class="sidebar-menu">
					<ul>
						<li class="menu-title">
							<span>Main Menu</span>
						</li>
						<li class="submenu">
							<a href="#"><i class="feather-grid"></i> <span> Dashboard</span> <span class="menu-arrow"></span></a>
							<ul>
								<li><a asp-action="Index">Admin Dashboard</a></li>
							</ul>
						</li>
						<li class="submenu">
							<a href="#"><i class="fas fa-graduation-cap"></i> <span> User Management</span> <span class="menu-arrow"></span></a>
							<ul>
								<li><a asp-action="UserManagement" asp-controller="Admin">Manage Users</a></li>
							</ul>
						</li>
						<li class="submenu">
							<a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Course Management</span> <span class="menu-arrow"></span></a>
							<ul>
								<li><a asp-action="AddCourse" asp-controller="Admin">Add Course</a></li>
								<li><a asp-action="AddCourseCont" asp-controller="Admin">Manage Courses</a></li>
								<li><a asp-action="CourseManagement" asp-controller="Admin">Update Course</a></li>
								<li><a asp-action="AddQuizes" asp-controller="Admin"> Add Quiz</a></li>
							</ul>
						</li>
						
						<li class="submenu">
							<a href="#"><i class="fas fa-file-invoice-dollar"></i> <span> Sales and Transactions</span> <span class="menu-arrow"></span></a>
							<ul>
								<li><a asp-action="ShowOrderHistory" asp-controller="Admin">View Transactions</a></li>
								
							</ul>
						</li>
						
						<li class="submenu">
							<a href="#"><i class="fa-solid fa-envelope"></i> <span> Notifications</span> <span class="menu-arrow"></span></a>
							<ul>
								<li><a asp-action="Index" asp-controller="Notify">Send Notifications</a></li>
							</ul>
						</li>
						
						<li class="submenu">
							<a href="#"><i class="fa fa-newspaper"></i> <span> Marketing Tools</span> <span class="menu-arrow"></span></a>
							<ul>
								<li><a asp-action="AddPromotion" asp-controller="Notify">Create Promotional Campaigns</a></li>
							</ul>
						</li>


						<li class="submenu">
							<a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Content Moderation</span> <span class="menu-arrow"></span></a>
							<ul>
								<li><a asp-action="ContentModeration" asp-controller="Admin">Manage Comments</a></li>
							</ul>
						</li>


					</ul>
				</div>
			</div>
		</div>
		<!-- /Sidebar -->
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
		<!-- Footer -->
		<footer>
			<p>COPYRIGHT © 2024 MASSTECH BUSINESS SOLUTIONS PVT LTD.</p>
		</footer>
		<!-- /Footer -->

	</div>
	<!-- /Page Wrapper -->
	</div>
	<!-- /Main Wrapper -->
	<!-- jQuery -->
	<script src="../AdminAssets/js/jquery-3.7.1.min.js"></script>

	<!-- Bootstrap Core JS -->
	<script src="../AdminAssets/js/bootstrap.bundle.min.js"></script>

	<!-- Feather Icon JS -->
	<script src="../AdminAssets/js/feather.min.js"></script>

	<!-- Slimscroll JS -->
	<script src="../AdminAssets/plugins/slimscroll/jquery.slimscroll.min.js"></script>

	<!-- Chart JS -->
	<script src="../AdminAssets/plugins/apexchart/apexcharts.min.js"></script>
	<script src="../AdminAssets/plugins/apexchart/chart-data.js"></script>

	<!-- Custom JS -->
	<script src="../AdminAssets/js/script.js"></script>
	@RenderSection("Scripts", required: false)
</body>

</html>